### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by goradical** [YunaiV/onemall#2]
mapstruct的convert类的方法用convert1，convert2这样排可不可以换成名字全部convert，因为方法重载调用的时候已经很明确调的是哪个转换器，除非特殊情况下，转换的源和目标类型不一样，此时用1,2区分下，不过这样极端情况应该不会太多

**Comment by YunaiV** [comment]
可以的，当时取这样的名字，也是偷懒。

因为 XXDO 转到目标 BO ，情况比较多。而 Java 的方法签名，是不考虑返回的，所以就直接 convert1、convert2 了。

**Comment by goradical** [comment]
谢谢！突然发现我表达的意思因为多打一个字而错了，我的意思因为重载，所有转换方法全部使用convert，如果要转换的目标类型一致，也就是方法的返回值一致，此时要转换的源（方法参数）类型不同也是OK的（重载），编码时IDE会列出所有方法，选定方法参数和自己要转换的源（方法参数）类型一样的方法就行了，极端情况源类型和目标类型一样，此时方法名一样，重载就不好使了，这时可以用1,2区分下，不过这种极端情况应该不多，不知道这次我说清楚了吗，看来自己得花时间写写博客来锻炼下自己的语言表达能力了，去年刚毕业，感觉要学的东西好多啊

**Comment by YunaiV** [comment]
可以看下

```Java
    @Mappings({})
    AdminBO convert(AdminDO adminDO);

    @Mappings({})
    AdminAuthenticationBO convert2(AdminDO admin);
```

Java 的重载，是不判断返回类型的，所以不得不在方法名做区分。
