### ISSUE TITLE
IP 域名映射

### ISSUE THREAD

**Issue by Darian1996** [YunaiV/onemall#23]
所有的 配置文件里边的 ip 都可以替换成域名，比如说 127.0.0.1 替换成 zookeeper.onemall.com 
这样，开发者配置 Host ，就可以不用更改源码就可以进行调试了。

**Comment by YunaiV** [comment]
谢谢建议，我考虑一波！

**Comment by YunaiV** [comment]
胖友的建议，已经应用到最新的代码，非常感谢哈。
