### ISSUE TITLE
token方案是否存在问题

### ISSUE THREAD

**Issue by DemoCap** [YunaiV/onemall#50]
# package:
> cn.iocoder.mall.systemservice.service.oauth.refreshAccessToken
# code
` 

>  OAuth2RefreshTokenDO refreshTokenDO = oauth2RefreshTokenMapper.selectById(refreshAccessTokenDTO.getRefreshToken());

        // 校验刷新令牌是否合法
        if (refreshTokenDO == null) { // 不存在
            throw ServiceExceptionUtil.exception(OAUTH2_REFRESH_TOKEN_NOT_FOUND);
        }
        if (refreshTokenDO.getExpiresTime().getTime() < System.currentTimeMillis()) { // 已过期
            throw ServiceExceptionUtil.exception(OAUTH_REFRESH_TOKEN_EXPIRED);
        }

        // 标记 refreshToken 对应的 accessToken 都不合法
        // 这块的实现，参考了 Spring Security OAuth2 的代码
        List<OAuth2AccessTokenDO> accessTokenDOs = oauth2AccessTokenMapper.selectListByRefreshToken(refreshAccessTokenDTO.getRefreshToken());
        accessTokenDOs.forEach(accessTokenDO -> deleteOAuth2AccessToken(accessTokenDO.getId()));

        // 创建访问令牌
        OAuth2AccessTokenDO oauth2AccessTokenDO = createOAuth2AccessToken(refreshTokenDO, refreshAccessTokenDTO.getCreateIp());
        // 返回访问令牌
        return OAuth2Convert.INSTANCE.convert(oauth2AccessTokenDO);
`

## 上述代码中对refreshToken对应的accessToken进行了移除，并重新创建了accessToken,但是并未刷新refreshToken的过期时间，
当refreshToken过期时间到达，会导致refreh-token接口错误

**Comment by YunaiV** [comment]
1. refreshToken 是固定过期时间噢。
2. refreshToken 到达过期时间，导致报错指的是？有具体的堆栈么？
