### ISSUE TITLE
功能图中出现重复部分

### ISSUE THREAD

**Issue by bigrotor187** [YunaiV/onemall#9]
![image](https://user-images.githubusercontent.com/34330670/61046245-3d372680-a40f-11e9-8092-92720d324373.png)

**Comment by qin4zhang** [comment]
感觉你可以提个PR了，哈哈

**Comment by bigrotor187** [comment]
> 感觉你可以提个PR了，哈哈

哈哈，我也觉得，估计艿艿么空~

**Comment by bigrotor187** [comment]
@qin4zhang  哈哈，我也觉得，估计艿艿么空修改~
